#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 TS testing and building your project before committing'

npm run eslint ||
(
    echo '🤢🤮🤢🤮 eslint. 🤢🤮🤢🤮';
    false;
)

npm run stylelint ||
(
    echo '🤢🤮🤢🤮 stylelint 🤢🤮🤢🤮'
    false;
)

echo '🤔🤔🤔🤔... Alright.... Code looks good to me... Trying to build now. 🤔🤔🤔🤔'

npm run test ||
(
    echo '❌👷🔨❌ Better call Bob... Because your build failed ❌👷🔨❌
            Next build failed: View the errors above to see why. 
    '
    false;
)


# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'
